service: aws-node-line-bot

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  environment:
    CHANNEL_ACCESS_TOKEN: "YOUR LINE CHANNEL ACCESS TOKEN"
    CHANNEL_SECRET: "YOUR LINE CHANNEL SECRET"

functions:
  bot:
    handler: handler.callback
    events:
      - http:
          path: callback
          method: post
          cors: true
